spring.application.name=everyChallenge

# 서버포트설정
server.port=8088

# mysql 연결 설정
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/everychallengedb?serverTimezone=UTC
spring.datasource.username = everychallenge
spring.datasource.password = 1234

# mybatis 설정
mybatis.mapper-locations = classpath:mapper/**/*.xml
#src/main/resources 하위의 mapper폴더 아래 모든 xml파일 및 폴더내의 xml파일
mybatis.type-aliases-package = com.everychallenge.domain
#CRUD 작업할 때 객체형태로 주고받는 DTO클래스가 있는 패키지 설정
mybatis.configuration.map-underscore-to-camel-case=true
#자바객체의 카멜케이스를 DB의 언더스코어로 자동변환 (예 userId -> user_id)

# 인코딩 설정
spring.http.encoding.charset = utf-8
spring.http.encoding.enabled = true
spring.http.encoding.force = true

# Thymeleaf 설정
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# 파일업로드 이미지 출력 경로
file.upload.path = /Users/sanghyeonjung/Documents/blog/item
uploadPath = /blog/item
spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 20MB
